module.exports.ErrorCode = {
    INVALID_ANALYTICS_QUERY: 0,
    0: "INVALID_ANALYTICS_QUERY",

    INTERNAL_ANALYTICS_ERROR: 1,
    1: "INTERNAL_ANALYTICS_ERROR",

    NOT_IMPLEMENTED: 2,
    2: "NOT_IMPLEMENTED",
    
    UNKNOWN_ERROR: 99,
    99: 'UNKNOWN_ERROR',
};

module.exports.HttpStatusToErrorCode = {
    400: ResultCode.INVALID_ANALYTICS_QUERY,
    500: ResultCode.INTERNAL_ANALYTICS_ERROR,
    501: ResultCode.NOT_IMPLEMENTED
};