version: 2.1

workflows:
  version: 2
  build:
    jobs:
      - build:
          matrix:
            parameters:
              node-version:
                - "10.24"
                - "12.13"
                - "14.20"
                - "16.17"
                - "18.17"
                - "20.18"

jobs:
  build:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
      - image: redis:7
    steps:
      - checkout
      - run:
          name: configure git
          command: |
            git config --global url."https://".insteadOf ssh://
            git config --global url."https://".insteadOf git://
      - run:
          name: install-npm
          command: npm install
      - run:
          name: test
          command: npm test
